[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-Clink-arg=-Tkernel/src/linker.lds",
    "-Cforce-frame-pointers=yes",
    "-Csymbol-mangling-version=v0",
]

[profile.dev]


[profile.release]
trim-paths = "all"
rustflags = [
    "--remap-path-prefix=kernel/src="
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins", "panic_abort"]
trim-paths=true
