cargo-features = ["profile-rustflags", "trim-paths"]

[workspace]
resolver = "2"
members = ["kernel", "crates/*", "user_rust/dummy"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
lto = true
trim-paths = "all"
