[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-g",
    "-Csymbol-mangling-version=v0",
    "-Clink-arg=-Tuser/userlib_macro/src/linker.lds",
    "-Cforce-frame-pointers=yes",
]