pub const CPU_NUM: usize = 2;

pub const MEMORY_SIZE: usize = 0x8000_0000; // 2GiB
 
pub const PHYSICAL_MEMORY_START: usize = 0x8000_0000;
 
pub const KERNEL_VIRTUAL_MEMORY_START: usize = 0xFFFF_FFFF_0000_0000;

pub const KERNEL_OFFSET: usize = KERNEL_VIRTUAL_MEMORY_START - PHYSICAL_MEMORY_START;