[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-Cforce-frame-pointers=yes",
]

[unstable]
build-std = ["core", "panic_abort"]