cargo-features = ["edition2024"]

[package]
name = "userlib_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true
